### ISSUE TITLE
fmgr_pkg_firewall_policy_sectionvalue does not work

### ISSUE THREAD

**Issue by sptschockaert** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#23]
**Problem Description:**
(there was no code of conduct for posting issues, so I apologize if any information is missing or if this is not the appropriate place to post issues - please correct me if/when needed)

I'm hitting AssertionError: wrong last_token received (napi.py:126) when using fmgr_pkg_firewall_policy_sectionvalue.
URL defined as follows in fmgr_pkg_firewall_policy_sectionvalue.py:148
`    perobject_jrpc_urls = [
        '/pm/config/adom/{adom}/pkg/{pkg}/firewall/policy/{policy}/{{policy}}/section value'
    ]`

URL as observed via browser:
`/pm/config/adom/root/pkg/FGT100F-SP/firewall/policy/477/section value`

Secondary issue: how does one pass in the policy ID using this mechanism in an ansible playbook? I cannot seem to find any working examples.
- I found [this](https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.1/docgen/fmgr_pkg_firewall_policy_sectionvalue.html) which is the API example code - it yields the same error as-is.
- I found [this](https://github.com/fortinet-ansible-dev/fortimanager-playbook-example), but there are no examples for section_value usage.

**System Details:**
FortiManager version: v6.4.5-build2288 210221 (GA)
Python version: 3.9.2
Ansible version: 2.10.7

**Stack trace:**
`Traceback (most recent call last):
  File "/home/thomasschockaert/.ansible/tmp/ansible-local-18508pbkpetlf/ansible-tmp-1618231963.5607805-18546-232691034977584/AnsiballZ_fmgr_pkg_firewall_policy_sectionvalue.py", line 102, in <module>
    _ansiballz_main()
  File "/home/thomasschockaert/.ansible/tmp/ansible-local-18508pbkpetlf/ansible-tmp-1618231963.5607805-18546-232691034977584/AnsiballZ_fmgr_pkg_firewall_policy_sectionvalue.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/thomasschockaert/.ansible/tmp/ansible-local-18508pbkpetlf/ansible-tmp-1618231963.5607805-18546-232691034977584/AnsiballZ_fmgr_pkg_firewall_policy_sectionvalue.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortimanager.plugins.modules.fmgr_pkg_firewall_policy_sectionvalue', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_pkg_firewall_policy_sectionvalue.py", line 222, in <module>
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_pkg_firewall_policy_sectionvalue.py", line 215, in main
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 366, in process_curd
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 156, in _process_with_mkey
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 130, in get_object
  File "/tmp/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload_qzp5plfh/ansible_fmgr_pkg_firewall_policy_sectionvalue_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 126, in _get_base_perobject_url
AssertionError: wrong last_token received`

**Playbook:**
`- hosts: all_fmgs
  gather_facts: no
  connection: httpapi
  collections:
  - fortinet.fortimanager
  vars:
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
    - name: Create test policy
      fmgr_pkg_firewall_policy:
        bypass_validation: False
        adom: "{{ fortimanager_target_adom }}"
        workspace_locking_adom: "{{ fortimanager_target_adom }}"
        workspace_locking_timeout: 30
        pkg: "ansible"
        state: present
        pkg_firewall_policy:
          policyid: 1
          name: policy-test
          srcintf: "Zone TST"
          srcaddr: HST_A
          dstintf: "Zone PRD"
          dstaddr: HST_B
          service: ALL
          schedule: always
          action: accept
          status: disable
    - name: test policy
      fmgr_pkg_firewall_policy_sectionvalue:
        bypass_validation: False
        workspace_locking_adom: "{{ fortimanager_target_adom }}"
        workspace_locking_timeout: 30
        state: present
        pkg_firewall_policy_sectionvalue:
          attr: label
          name: Test Section
    - name: Commit workspace
      fmgr_dvmdb_workspace_commit:
        bypass_validation: False
        adom: "{{ fortimanager_target_adom }}"
        workspace_locking_adom: "{{ fortimanager_target_adom }}"
        workspace_locking_timeout: 30`

**Comment by chillancezen** [comment]
hi @sptschockaert, 
it will be fixed in Galaxy collection `2.0.3`

there are three parameters needed, please see https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.3/docgen/fmgr_pkg_firewall_policy_sectionvalue.html

**Comment by chillancezen** [comment]
`2.0.3` has been released.
install it by :`ansible-galaxy collection install -fn fortinet.fortimanager`
