### ISSUE TITLE
Error on modify dynamic mapping with fmgr_firewall_address

### ISSUE THREAD

**Issue by sergioolovrap-lmit** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#64]
Hello,
this is the playbook:

```
- hosts: FMG
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:   
   - name: Add dynamic mapping
     fmgr_firewall_address:
        bypass_validation: False
        adom: IT-LM
        state: present
        firewall_address:
           name: ansible-try
           dynamic_mapping:
             - 
                _scope:
                  name: 'FW-NAME'
                  vdom: 'root'
                subnet: '10.36.25.0/24'
                obj-type: 'ip'
                type: 'ipmask'
```
Error log:

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_firewall_address.py", line 2191, in <module>
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_firewall_address.py", line 2184, in main
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 1112, in process_curd
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 1222, in check_versioning_mismatch
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 1235, in check_versioning_mismatch
  File "/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py", line 1226, in check_versioning_mismatch
AssertionError
fatal: [FMG]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-111342yj6s6nv/ansible-tmp-1686128289.2505593-11259-150982152178915/AnsiballZ_fmgr_firewall_address.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_firewall_address.py\", line 2191, in <module>\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_firewall_address.py\", line 2184, in main\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 1112, in process_curd\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 1222, in check_versioning_mismatch\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 1235, in check_versioning_mismatch\n  File \"/tmp/ansible_fmgr_firewall_address_payload_9tve2ftp/ansible_fmgr_firewall_address_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 1226, in check_versioning_mismatch\nAssertionError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **************************************************************************************************************************************************************************************
FMG             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

I dont understand the error, dynamic mapping is a list and i think i complete all information needed.
Could you help me?
Thanks
Sergio

**Comment by dux-fortinet** [comment]
Hi Sergio,
According to the definition, _scope is a list of dictionaries. So please try

```
_scope:
  -  name: 'FW-NAME'
     vdom: 'root'
``` 
instead of
```
_scope:
  name: 'FW-NAME'
  vdom: 'root'
``` 

Furthermore, if you want to get more details about how FortiManager Ansible Collection works, you can add enable_log:

``` 
tasks:   
   - name: Add dynamic mapping
     fmgr_firewall_address:
        enable_log: true
        bypass_validation: False
        ...
``` 
and you will find the log file in /tmp/fortimanager.ansible.log

Thanks,
Xinwei
